# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint Build

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - 'master'

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          if (Test-Path -path .\requirements.txt) { pip install -r requirements.txt }

      - name: Style with black
        uses: wearerequired/lint-action@v1.11.1
        with: 
          black: true
          auto_fix: true
          git_email: "franklinmoy3@gmail.com"
          commit_message: "GH Action: Fix code style issues with ${linter}"
